### ISSUE TITLE
checklist for `0.0.9` release

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#164]
Submission date: sometime between 15th-17th February

- [x] 1. Check all aspects of new effect size _r_ for Mann-Whitney test and _d_/_g_ for _t_-test 
(esp. between versus within; central versus noncentral, equal versus unequal variance; #179)

- [ ] 2. Implement the new effect size _r_ for one-sample Wilcoxon test (also change statistic from _W_ to _V_)

- [ ] 3. Implement the new Cohen's _d_ and Hedge's _g_ for one-sample _t_-test

- [x] 4. Change the defaults from central to noncentral

- [x] 5. Add documentation for effect size _d_ and _g_ for _t_ test 

- [x] 6. Add documentation for effect size _r_ for Mann-Whitney test 

- [x] 7. Add tests for the new effect size functions/computations 

- [x] 8. Add `results.subtitle` argument to both `ggpiestats` and `ggbarstats` which can help avoid expensive stats computations if the user is not interested in these details.

Up for discussion-
Possibly drop the log-transformation of V and W in Mann-Whitney/Wilcoxon? 
Typically this number is humongous if _p_ < 0.001 and completely mangles the subtitle; so find an alternative.

**Comment by IndrajeetPatil** [comment]
@ibecav Let's follow this checklist to make sure all required changes are done before submission.

**Comment by ibecav** [comment]
Will do on the checklist

**Comment by IndrajeetPatil** [comment]
Will you be able to add documentation for the new effect sizes? It'll be good to have it in the release itself rather than adding it in the next release.  

I think this is something that needs to be prioritized over everything else since people will wonder how these were computed. Even a single sentence summaries in Description should do the job.

**Comment by ibecav** [comment]
Okay based on this doco first and then polish up the discrepancy in `subtitle_mann_nonparametric` I'll be lucky to get both done.

**Comment by ibecav** [comment]
Submitting PR for the t test doco adding a lot of doco.  No changes to tests needed and I think I got all the lint.  Sorry my latex is rusty otherwise I would have made the math prettier.

**Comment by IndrajeetPatil** [comment]
Do you also want to add documentation for effect size for the Mann-Whitney test in the same PR or a different one?

**Comment by ibecav** [comment]
Same PR ... done.  May or may not get to the issue about differing results for Mann Whitney tonight.  Have about an hour but why don't you process these when you can if they're suitable

**Comment by IndrajeetPatil** [comment]
Do you plan to add something today, Chuck? If not, I think we are ready for submission. 

I'd like to submit by tonight.

**Comment by ibecav** [comment]
Had hoped to take a final look at wilcoxon but if you don’t see anything by 2p go ahead and do your thing I have some real life plans that may intervene and don’t want to hold you up

**Comment by IndrajeetPatil** [comment]
Sounds good.

**Comment by IndrajeetPatil** [comment]
The `0.0.9` version is now on `CRAN` (https://cran.r-project.org/web/packages/ggstatsplot/index.html), but will keep this open until all the pending items have been resolved.

**Comment by ibecav** [comment]
kk, so you're ready for PR's again? Just posted about #162

**Comment by IndrajeetPatil** [comment]
Yepp, feel free to make new PRs

**Comment by IndrajeetPatil** [comment]
In the `effsize_t_parametric` function, the following line is redundant, right?
https://github.com/IndrajeetPatil/ggstatsplot/blob/8385a8cc8f19908350f87e86f19d9a617f271bd2/R/helpers_ggbetween_t_subtitles.R#L914

**Comment by ibecav** [comment]
Yepp, it's a leftover artifact from my many adjustments

**Comment by ibecav** [comment]
Since my next PR is in that file as well as the one in progress I'll be happy to remove it.
