### ISSUE TITLE
checklist for 0.4.0 cran submission

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#411]
To be released by the end of May

# CRAN submissions

- [x] `ipmisc` (2.0.0)
- [x] `statsExpressions` (0.4.0)
- [x] `pairwiseComparisons` (0.3.0)
- [x] `tidyBF` (0.2.0)
- [x] `broomExtra` (2.6.0)
- [x] `correlation` (0.2.0)
- [x] `effectsize` (0.3.0)

# high priority: issues to resolve

- [ ] rely on `effectsize` to calculate effect sizes + CIs in `ggcoefstats`
- [ ] get rid of `groupedstats` as a dependency (related to #406)
 
# low priority

- [ ] adding support for partial correlations (#64)

**Comment by IndrajeetPatil** [comment]
closed in https://github.com/IndrajeetPatil/ggstatsplot/commit/0702036a40eeaca6f23b80960fb8f91320d17474
