### ISSUE TITLE
`ggstatsplot 0.6.8` checklist

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#496]
- [x] remove all the unnecessary reexports from `easystats` packages
- [x] change to `format_num` everywhere
- [ ] use `tidy_model_parameters`, etc. from `statsExpressions`?
- [x] change all `mean.*` arguments to `centrality.*` in `ggbetweenstats` and `ggwithinstats`
- [x] replace superseded `dplyr` scoped verbs (like `mutate_at`, `select_if`, etc.) with `across`
- [x] remove reference to `aes_string` in `ggcoefstats`
- [x] restructure reference and articles section like [this](https://github.com/ggobi/ggally/blob/master/_pkgdown.yml)?
- [x] update docs to reflect the move from `rcompanion` to `effectsize`
- [x] retire `conf.type` argument everywhere it is mentioned in `statsExpressions` calls
- [x] remove all detailed explanations in `ggcoefstats`, since the purpose of that vignette is not to explain any model to the user but just to demonstrate that the model is supported
