### ISSUE TITLE
plans for for `0.8.0` release

### ISSUE THREAD

**Issue by IndrajeetPatil** [IndrajeetPatil/ggstatsplot#535]
- [x] use pretty printing for sample sizes for each group in `ggbetweenstats` and `ggwithinstats`
- [x] remove duplicated `svyglm` in `ggcoefstats`
- [x] I think this is unnecessary 
https://github.com/IndrajeetPatil/ggstatsplot/blob/b69dfcd25e2282685003b6a92b6b240a4a649a85/R/ggcorrmat.R#L172
- [x] remove `title.prefix` in `grouped_` functions
- [x] update `NEWS` to include this context (https://github.com/IndrajeetPatil/ggstatsplot/issues/540)
- [x] add something like this to dependencies vignette? https://cran.r-project.org/web/packages/pkgndep/vignettes/pkgndep.html
- [x] conditionally use `ggExtra`
- [x] enumerate `FAQ` sections
- [x] catch up with updates to `defaults` info in `ggstatsplot` slide deck
- [x] add example to docs: https://github.com/IndrajeetPatil/ggstatsplot/issues/538
- [x] include citation in all vignettes
- [x] add to  FAQ: https://github.com/IndrajeetPatil/ggstatsplot/issues/542
- [x] use pretty-printing here
https://github.com/IndrajeetPatil/ggstatsplot/blob/9b75e01b826941aef10eab4305c1ca9ddc8e90b1/R/helpers_ggcatstats_graphics.R#L77
- [x] add lifecycle badges to README and vignettes
- [x] use `ggcorrplot` conditionally
- [x] add to FAQ https://github.com/IndrajeetPatil/ggstatsplot/issues/475
- [x] delete `docs/` folder and regenerate the entire website
- [x] remove references to `itdepends` in `README`; requires `GitHub` credentials
- [x] add `@noRd` to all internal functions to avoid issues like #https://github.com/IndrajeetPatil/ggstatsplot/issues/587
- [x] add `point.args` to `ggwithinstats`
- [x] use `insight::check_if_installed`
- [x] just like other functions, `xlab` and `ylab` arguments for `ggcoeftstats` should be `NULL`
- [x] make note that robust effect size has changed from xi to AKP
- [x] remove re-export of `effectsize`
- [x] retire `ggstatsplot.layer` argument? if users are specifying a different theme, they really want that theme and not polished version `ggstatsplot` is providing
- [x] add `geom` lists to individual fun docs
- [x] I don't think this is needed since neither `ggbetweenstats` nor `ggwithinstats` use `fill`:
https://github.com/IndrajeetPatil/ggstatsplot/blob/7427c058b2ff7c5c0ce116575d32e99ed78277d4/R/helpers_ggbetweenstats_graphics.R#L294
- [x] double-check if specifying this across `geom`s is necessary in `ggbetweenstats` and `ggwithinstats`
https://github.com/IndrajeetPatil/ggstatsplot/blob/7427c058b2ff7c5c0ce116575d32e99ed78277d4/R/ggbetweenstats.R#L364
- [x] make `extract_stats` more comprehensive in terms of dataframes it returns (centrality data, descriptive data, etc.)
- [x] This is still necessary: https://github.com/IndrajeetPatil/ggstatsplot/blob/e945b3420f360105232ec6a918db961534259313/README.Rmd#L2-L4

**Comment by IndrajeetPatil** [comment]
Add example to FAQ

```r
library(ggstatsplot)

grouped_ggscatterstats(
  mtcars,
  wt,
  mpg,
  grouping.var = am,
  ggplot.component = list(ggplot2::labs(title = NULL))
)
```

**Comment by IndrajeetPatil** [comment]
Provide stats argument as a list:

``` r
library(statsExpressions)
#> Registered S3 methods overwritten by 'lme4':
#>   method                          from
#>   cooks.distance.influence.merMod car 
#>   influence.merMod                car 
#>   dfbeta.influence.merMod         car 
#>   dfbetas.influence.merMod        car

foo <- function(data, x, y) {
  x <- rlang::ensym(x)
  y <- rlang::ensym(y)
  
  .f.args <- list(var.equal = FALSE)
  
  eval(rlang::call2(
    .ns = "statsExpressions",
    .fn = "two_sample_test",
    data = data,
    x = x,
    y = y,
    !!!.f.args
  ))
}

foo(mtcars, am, wt)
#> # A tibble: 1 x 14
#>   term  group mean.group1 mean.group2 statistic df.error p.value method estimate
#>   <chr> <chr>       <dbl>       <dbl>     <dbl>    <dbl>   <dbl> <chr>     <dbl>
#> 1 wt    am           3.77        2.41      5.49     29.2 6.27e-6 Welch…     1.84
#> # … with 5 more variables: conf.level <dbl>, conf.low <dbl>, conf.high <dbl>,
#> #   effectsize <chr>, expression <list>
```

<sup>Created on 2021-03-04 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
``` r
library(ggstatsplot)
library(nlme)

# variance increases with a power of the absolute fitted values
mod_gnls <- gnls(
  model = weight ~ SSlogis(Time, Asym, xmid, scal),
  data = Soybean,
  weights = varPower()
)

ggcoefstats(
  x = mod_gnls,
  title = "nonlinear model using generalized least squares"
)
```

![](https://i.imgur.com/CI1VCjK.png)

<sup>Created on 2021-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
``` r
check_outlier <- function(var, coef = 1.5) {
  quantiles <- stats::quantile(x = var, probs = c(0.25, 0.75), na.rm = TRUE)
  IQR <- quantiles[2] - quantiles[1]
  (var < (quantiles[1] - coef * IQR)) | (var > (quantiles[2] + coef * IQR))
}

waldo::compare(
  check_outlier(mtcars$wt, coef = 3),
  performance::check_outliers(mtcars$wt, method = "iqr", threshold = list("iqr" = 3)),
  ignore_attr = TRUE
)
#> ✓ No differences
```

<sup>Created on 2021-04-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by IndrajeetPatil** [comment]
add following to README

````
# Troubleshooting

- `ERROR: dependencies ‘gmp’, ‘Rmpfr’ are not available for package ‘PMCMRplus’` or `ERROR: dependency ‘pairwiseComparisons’ is not available for package ‘ggstatsplot’` on Linux when installing `ggstatsplot` package.

It seems that your operating system lacks `gmp` and `Rmpfr` development libraries.

If you use Ubuntu, you can install these dependencies:

```
sudo apt-get install libgmp3-dev
sudo apt-get install libmpfr-dev
```
````

**Comment by IndrajeetPatil** [comment]
```md
## Test environments

* local Windows install, R 4.1.0

* ubuntu 14.04 (on gitub-actions-ci), R 4.1.0

* win-builder (devel and release)

## R CMD check results

0 errors | 0 warnings | 0 note

  - Maintenance release with a few bug fixes.

## revdepcheck results

Currently no reverse dependencies.

```
